spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dentflow
    username: eternal
    password: eternal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: dentflowec@gmail.com
    password: mdkuporgyrpcyxqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


